@baseUrl = http://localhost:8081

### 1) Create a new user
POST {{baseUrl}}/user/signup
Content-Type: application/json

{
  "username": "testuser_password2",
  "email": "testpassword2@gmail.com",
  "password": "oldpass123"
}

###

### 2) Change the password for that user
# Replace the userId below with the _id returned from signup
@userId = yor_Id_Here

PUT {{baseUrl}}/user/{{userId}}/password
Content-Type: application/json

{
  "currentPassword": "oldpass123",
  "newPassword": "newpass123",
  "confirmPassword": "newpass123"
}

###

### 3) Try logging in with the OLD password (should fail)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "username": "testuser_password1",
  "password": "oldpass123"
}

###

### 4) Try logging in with the NEW password (should succeed)
POST {{baseUrl}}/user/login
Content-Type: application/json

{
  "username": "testuser_password2",
  "password": "newpass123"
}

###

### Delete account with password confirmation
DELETE {{baseUrl}}/user/{{userId}}/delete-account
Content-Type: application/json

{
  "password": "newpass123"
}

###