
# @name createAdmin
POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "Admin_Test_5",
    "email" : "Nope@NotGonna.com",
    "password" : "passwordMoreLikePissword"
}

###
@adminTestId1 = {{createAdmin.response.body.$._id}}

###

POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "1tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/69a872661eae65cd012dd496/admin
Content-Type: application/json

###


###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "69b19b797098075437cca5f5",
    "username" : "1Tochi Edit",
    "email" : "1cdonEdited@notagmail.com",
    "password" : "dwwrwraaa"
}

###
GET  http://localhost:8081/user/69a872661eae65cd012dd496
Content-Type: application/json 

###
GET  http://localhost:8081/user/697117139e6a43431cf663cd
Content-Type: application/json 

###
POST  http://localhost:8081/user/69eb956e5131ddfa0dd1e56a/delete
Content-Type: application/json

###
POST  http://localhost:8081/user/deleteAll